const nbalogo = {
    "AtlantaHawks":["9168_atlanta_hawks-primary-2016", "https://i.imgur.com/cnCt0pi.png"],
BostonCeltics:["bostonceltics","https://i.imgur.com/6BjmvB9.png"],
BrooklynNets:["137_brooklyn-nets-primary-2013","https://i.imgur.com/Yo2SWH5.png"],
CharlotteHornets:["1926_charlotte__hornets_-primary-2015","https://i.imgur.com/q0F98Vr.png"], 
ChicagoBulls:["chicagobulls","https://i.imgur.com/nBXdIZa.png"], 
ClevelandCavaliers:["6921_cleveland_cavaliers-primary-2018","https://i.imgur.com/SQ8IRGe.png"], 
DallasMavericks:["3463_dallas_mavericks-primary-2018","https://i.imgur.com/IoHSBay.png"], 
DenverNuggets:["8926_denver_nuggets-primary-2019","https://i.imgur.com/9UQCcCy.png"], 
DetroitPistons:["2164_detroit_pistons-primary-2018","https://i.imgur.com/w8IdQ5o.png"],
GoldenStateWarriors:["3152_golden_state_warriors-primary-2020","https://i.imgur.com/pjT1MT2.png"], 
HoustonRockets:["6830_houston_rockets-primary-2020","https://i.imgur.com/jVKqsCT.png"], 
IndianaPacers:["4812_indiana_pacers-primary-2018","https://i.imgur.com/cF7ZE6m.png"], 
LAClippers:["5462_los_angeles_clippers-primary-2016","https://i.imgur.com/TXXgQsL.png"], 
LALakers:["Lakers","https://i.imgur.com/uM89Dje.png"], 
MemphisGrizzlies:["4373_memphis_grizzlies-primary-2019","https://i.imgur.com/bR4g8sF.png"], 
MiamiHeat:["maimiheat","https://i.imgur.com/5Sojwa8.png"],
MilwaukeeBucks:["8275_milwaukee_bucks-primary-2016","https://i.imgur.com/l5Mk2y0.png"], 
MinnesotaTimberwolves:["9669_minnesota_timberwolves-primary-2018","https://i.imgur.com/8Kd7LHm.png"], 
NewOrleansPelicans:["2681_new_orleans_pelicans-primary-2014","https://i.imgur.com/qbQcmgr.png"], 
NewYorkKnicks:["knicks","https://i.imgur.com/7G0Sipn.png"], 
OklahomaCityThunder:["khmovcnezy06c3nm05ccn0oj2", "https://i.imgur.com/Kzzjylu.png"], 
OrlandoMagic:["magic","https://i.imgur.com/W0mpDPp.png"], 
PhiladelphiaSixers:["7034_philadelphia_76ers-primary-2016","https://i.imgur.com/AJFWuzK.png"], 
PhoenixSuns:["4370_phoenix_suns-primary-2014","https://i.imgur.com/NyvEymP.png"],
PortlandTrailBlazers:["9725_portland_trail_blazers-primary-2018","https://i.imgur.com/9woaLrf.png"], 
SacramentoKings:["4043_sacramento_kings-primary-2017","https://i.imgur.com/bZf4Z8x.png"], 
SanAntonioSpurs:["2547_san_antonio_spurs-primary-2018","https://i.imgur.com/pcan3JR.png"], 
TorontoRaptors:["4578_toronto_raptors-primary-2016","https://i.imgur.com/fN1bg4o.png"], 
UtahJazz:["6749_utah_jazz-primary-2017","https://i.imgur.com/7l9QU1W.png"],
WashingtonWizards:["5671_washington_wizards-primary-2016","https://i.imgur.com/IIGRDVX.png"]
}
module.exports = nbalogo;